[project]
name = "quant_strategy_lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "unicorn>=2.1.4",
    "mcp",
    "fastapi",
]
